exp_prefix: "cart_pole"
epoch: 3 # TODO
elite_ratio: 0.06

populate_num: 50
init_params: [0.1,   2,    1, 0, ] # delta ^ c1 - delta_max ^ c1 + c2 * theta * dot_theta + c3; fourth is k in dot(phi) <= - c0
lower_bound: [0.001, 1, 0.01, 0] # Default: [1, 0, 0]; TODO: don't c1, c2, k have to be strictly positive (nonzero)?
upper_bound: [1, 3, 3, 3]
init_sigma_ratio: 0.3 # initial sigma = init_sigma_ratio * (upper_bound - lower_bound)
noise_ratio: 0.01 # noise = noise_ratio * (upper_bound - lower_bound)
evaluator: "CartPoleEvaluator"
