exp_prefix: "cart_pole"
epoch: 1
elite_ratio: 0.1
populate_num: 10
init_params: [2, 1, 1] # theta ^ c1 - theta_max ^ c1 + c2 * dot_theta + c3
lower_bound: [2, 0, 0]
upper_bound: [10, 10, 10]
init_sigma_ratio: 0.3 # initial sigma = init_sigma_ratio * (upper_bound - lower_bound)
noise_ratio: 0.01 # noise = noise_ratio * (upper_bound - lower_bound)
evaluator: "CartPoleEvaluator"