exp_prefix: "flying_pend"
epoch: 3 # default
elite_ratio: 0.06 # default

populate_num: 50
init_params: [1.0, 0.0, 5.0] #[0.1, 2, 1, 0] # theta ^ c1 - theta_max ^ c1 + c2 * theta * dot_theta + c3; fourth is k in dot(phi) <= - k phi
lower_bound: [0.01, 0.0, 0.01] #[0.01, 1, 0.01, 0] # Default: [1, 0, 0]; TODO: don't c1, c2, k have to be strictly positive (nonzero)?
upper_bound: [50.0, 5.0, 50.0] #[1, 3, 3, 3] # TODO: interesting! Last time Tianhao let the exponent be upper bounded by 1.0, but the upper bound should be >>1.0, no? Is that why we got really suboptimal results last time?
init_sigma_ratio: 0.3 # initial sigma = init_sigma_ratio * (upper_bound - lower_bound)
noise_ratio: 0.01 # noise = noise_ratio * (upper_bound - lower_bound)
evaluator: "FlyingPendEvaluator"